services:
  - type: web
    name: contemplation-flow
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      cd backend && pip install -e .
      cd ../frontend && npm install && npm run build
    startCommand: cd backend && uvicorn src.server:get_app --host 0.0.0.0 --port $PORT --factory
    envVars:
      - key: ASAM_DB_URL
        value: postgresql+asyncpg://postgres:nejqij-0xygxi-kogHir@db.mfzbpincchxrgqwagpjw.supabase.co:5432/postgres
      - key: ASAM_JWT_SECRET
        generateValue: true
      - key: ASAM_OPENAI_TOKEN
        sync: false
      - key: ASAM_SUPABASE_URL
        sync: false
      - key: ASAM_SUPABASE_KEY
        sync: false
      - key: ASAM_HOST
        value: 0.0.0.0
      - key: ASAM_PORT
        value: $PORT
      - key: ASAM_PROD
        value: true
    healthCheckPath: /health
    autoDeploy: true 