"""add feedback comments column in messages

Revision ID: acb52eb484f9
Revises: c79a76090dd3
Create Date: 2025-07-06 10:15:47.001781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb52eb484f9'
down_revision: Union[str, Sequence[str], None] = 'c79a76090dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('feedback_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'feedback_comment')
    # ### end Alembic commands ###
