"""remove documents + user connection

Revision ID: c79a76090dd3
Revises: 87847983da49
Create Date: 2025-07-06 00:16:38.651946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79a76090dd3'
down_revision: Union[str, Sequence[str], None] = '87847983da49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('source_documents_user_id_fkey'), 'source_documents', type_='foreignkey')
    op.drop_column('source_documents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('source_documents_user_id_fkey'), 'source_documents', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
