"""make_source_documents_shared_remove_user_id

Revision ID: bf454a893619
Revises: dec30c2ef7ae
Create Date: 2025-08-04 21:00:17.749350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf454a893619'
down_revision: Union[str, Sequence[str], None] = 'dec30c2ef7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_content_generation_message_id', 'content_generations', ['message_id'], unique=False)
    op.create_index('idx_message_feedback_type', 'messages', ['feedback_type'], unique=False)
    op.drop_constraint(op.f('source_documents_user_id_fkey'), 'source_documents', type_='foreignkey')
    op.drop_column('source_documents', 'user_id')
    op.drop_index(op.f('idx_user_profiles_phone'), table_name='user_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_profiles_phone'), 'user_profiles', ['phone_number'], unique=False)
    op.add_column('source_documents', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('source_documents_user_id_fkey'), 'source_documents', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_message_feedback_type', table_name='messages')
    op.drop_index('idx_content_generation_message_id', table_name='content_generations')
    # ### end Alembic commands ###
