"""add input/output tokens column in messages

Revision ID: a433b720c32e
Revises: acb52eb484f9
Create Date: 2025-07-06 10:23:37.435178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a433b720c32e'
down_revision: Union[str, Sequence[str], None] = 'acb52eb484f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'output_tokens')
    op.drop_column('messages', 'input_tokens')
    # ### end Alembic commands ###
