"""add blacklist token table

Revision ID: e6fb5e0a0c35
Revises: a433b720c32e
Create Date: 2025-07-07 19:26:59.610962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fb5e0a0c35'
down_revision: Union[str, Sequence[str], None] = 'a433b720c32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_blacklisted_tokens_expires_at', 'blacklisted_tokens', ['expires_at'], unique=False)
    op.create_index('idx_blacklisted_tokens_token', 'blacklisted_tokens', ['token'], unique=False)
    op.create_index('idx_blacklisted_tokens_user_id', 'blacklisted_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blacklisted_tokens_user_id', table_name='blacklisted_tokens')
    op.drop_index('idx_blacklisted_tokens_token', table_name='blacklisted_tokens')
    op.drop_index('idx_blacklisted_tokens_expires_at', table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
