"""merge meditations and contemplation cards in one

Revision ID: f44ef7a8f38b
Revises: b8c2f9a648cb
Create Date: 2025-07-05 15:25:13.601847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f44ef7a8f38b'
down_revision: Union[str, Sequence[str], None] = 'b8c2f9a648cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('content_type', postgresql.ENUM('IMAGE', 'VIDEO', 'AUDIO', name='content_type_enum'), nullable=False),
    sa.Column('content_path', sa.String(), nullable=True),
    sa.Column('cc_text', sa.Text(), nullable=True),
    sa.Column('cc_theme', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_generations_type', 'content_generations', ['content_type'], unique=False)
    op.create_index('idx_content_generations_user_created', 'content_generations', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_meditations_user_created'), table_name='meditations')
    op.drop_table('meditations')
    op.drop_index(op.f('idx_contemplation_cards_user_created'), table_name='contemplation_cards')
    op.drop_table('contemplation_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contemplation_cards',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('contemplation_cards_conversation_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('contemplation_cards_message_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('contemplation_cards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('contemplation_cards_pkey'))
    )
    op.create_index(op.f('idx_contemplation_cards_user_created'), 'contemplation_cards', ['user_id', 'created_at'], unique=False)
    op.create_table('meditations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mode', postgresql.ENUM('VIDEO', 'AUDIO', name='meditation_mode_enum'), autoincrement=False, nullable=False),
    sa.Column('voice_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('meditations_conversation_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('meditations_message_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('meditations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meditations_pkey'))
    )
    op.create_index(op.f('idx_meditations_user_created'), 'meditations', ['user_id', 'created_at'], unique=False)
    op.drop_index('idx_content_generations_user_created', table_name='content_generations')
    op.drop_index('idx_content_generations_type', table_name='content_generations')
    op.drop_table('content_generations')
    # ### end Alembic commands ###
