"""location in chunk is an integer

Revision ID: 6df72e17152e
Revises: 76a224404db4
Create Date: 2025-07-07 22:09:11.080027

"""

from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6df72e17152e"
down_revision: Union[str, Sequence[str], None] = "76a224404db4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "content_generations",
        "conversation_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "content_generations", "message_id", existing_type=sa.UUID(), nullable=False
    )
    op.add_column("document_chunks", sa.Column("location", sa.Text(), nullable=False))
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=False,
    )
    op.alter_column(
        "document_chunks", "model_used", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("document_chunks", "loc")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("loc", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "document_chunks", "model_used", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        nullable=True,
    )
    op.drop_column("document_chunks", "location")
    op.alter_column(
        "content_generations", "message_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "content_generations", "conversation_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
