"""temp: allow is_signed_in to be not nullable

Revision ID: 76a224404db4
Revises: 158fd9e1573a
Create Date: 2025-07-07 19:54:12.452634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a224404db4'
down_revision: Union[str, Sequence[str], None] = '158fd9e1573a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'is_signed_in',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'is_signed_in',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
